name: ynfny
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI and responsive design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  web: ^1.1.0
  vector_math: ^2.1.4
  
  # Feature dependencies
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  permission_handler: ^11.1.0
  geolocator: ^10.1.0
  
  # Supabase integration (preserve current version for compatibility)
  supabase_flutter: ^2.5.6
  
  # Media handling
  image_picker: ^1.1.2
  record: ^6.0.0
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  video_player: ^2.8.1
  camera: ^0.11.0+2
  
  # Payment processing
  pay: ^3.2.1
  stripe_platform_interface: ^11.5.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
