name: ynfny
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
<<<<<<< HEAD
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI and responsive design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  web: ^1.1.0
  vector_math: ^2.1.4
  
  # Feature dependencies
=======
  sdk: ^3.6.0

dependencies:
  flutter:       # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
  
  # 🚨 CRITICAL: Core UI and responsive design - DO NOT REMOVE OR MODIFY
  sizer: ^2.0.15              # Required for responsive design system
  flutter_svg: ^2.0.9        # Required for SVG icon support
  google_fonts: ^6.1.0       # Required for typography (replaces local fonts)
  shared_preferences: ^2.2.2 # Required for local data storage
  web: ^1.1.1
  
  # Feature dependencies - safe to modify
>>>>>>> b1f9c438f65d3f7093efb1d909f7b1e8e83c8cb5
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  camera: ^0.10.5+5
  permission_handler: ^11.1.0
  geolocator: ^10.1.0
  
<<<<<<< HEAD
  # Supabase integration (preserve current version for compatibility)
  supabase_flutter: ^2.5.6
=======
  # Supabase integration
  supabase_flutter: ^2.9.1
>>>>>>> b1f9c438f65d3f7093efb1d909f7b1e8e83c8cb5
  
  # Media handling
  image_picker: ^1.1.2
  record: ^6.0.0
  path_provider: ^2.1.5
  file_picker: ^8.1.7
<<<<<<< HEAD
  video_player: ^2.8.1
=======
>>>>>>> b1f9c438f65d3f7093efb1d909f7b1e8e83c8cb5
  
  # Payment processing
  pay: ^3.2.1
  stripe_platform_interface: ^11.5.0
<<<<<<< HEAD
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
=======

  universal_html: ^2.2.4
dev_dependencies:
  flutter_test:    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter   # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  flutter_lints: ^5.0.0 # 🚨 CRITICAL: Required for code quality - DO NOT REMOVE

flutter:
  uses-material-design: true # 🚨 CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - assets/
    - assets/images/
  # 🚨 CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)
  
  # 🚨 CRITICAL FONTS RULE: 
  # - THIS PROJECT USES GOOGLE FONTS INSTEAD OF LOCAL FONTS
  # - DO NOT ADD ANY LOCAL FONTS SECTION OR FONT FILES
  # - ALL FONTS MUST BE LOADED VIA google_fonts PACKAGE
  # - DEFAULT FONT: Use GoogleFonts.inter() unless specified otherwise
>>>>>>> b1f9c438f65d3f7093efb1d909f7b1e8e83c8cb5
